### PR TITLE
Add build stage to Dockerfile

### PR DESCRIPTION
**Pull request by MrEmanuel**
- Add build stage to Dockerfile
- Remove unnecessary copy steps in Dockerfile
- Update Readme with simpler steps
- Update Readme to clarify where to get more info about the token
- Add a catch and print useful http status in error message if token is not correct

### CODE REVIEW

**Comment by damfle** [comment]
Are you sure it works without copying the example config file ? When I tried config file was included in the deps so it couldn't cache deps as it couldn't find config file.

I don't understand what you're trying to achieve too. Look like your building a container (containing every files), then copying the container inside another. This feature is usefull when you actually have to build thing; like Rust app that you can statically build and then use without distrib or with Google's distroless; or building pyc in python, but for deno the only thing needed in the container are the cached dependencies, so no overhead is created.

I agree with removing the cache mods or deps as they are redundant (better to remove deps caching and keep mods one).

Real game changer would be to have the config file in yaml or json and don't import it so we can dynamically load it (keep the example and mount the production version)

**Comment by MrEmanuel** [comment]
Ok, so maybe I'm missing a few things here.
I removed my `configs.example.ts` and just added a `configs.ts` file like the README instructions say. I assumed the example file wasn't needed and was supposed to be removed. That's why I also removed it from the build step. But you say it's a dependency? 

Regarding the build step. Maybe I'm missing something here too about how deno works and how it handles dependencies. This is my first deno project. 
But even if it doesn't build files the same way node does, I think it's still useful to automate the build step and only require the user to run the `docker run` command.

Regarding the mount of the `configs.ts`, I looked in to it yesterday but I couldn't make sense of it. Deno doesn't recognize the token value if it's not mounted and I don't really know why. 
I could implement `dotenv` and keep the token in a `.env` file if that's an acceptable solution.

**Comment by damfle** [comment]
config.ts is required to cache dependecies. Not config.example.ts. But if you do this your config.ts (with secrets) will be bundled inside your container and you don't want this (even if for now there is no dockerignore so its copied anyway). So config.example.ts was used to download deps at build time.

For the build step, caching deps at container build time is efficient with deno and does not cause overhead. The deno runtime do everything and we're not bundling the bot nor creating an executable out of it (which can be done with Deno). Build step is unnecessary. This build step is building a container, not the app, which is a bit useless in this case.

Again for the mount. To be able to build the container you need a config.ts. So the one used per default is config.example.ts so that you MUST volume mount your config.

.env is fine. But the issue is more that all the secrets are bundled into a config ts file. I think this is this part of the code that need to be redone

**Comment by damfle** [comment]
Here an example with distroless (don't work as the app is not compatible)
`
# Start the build stage
# Start from a base image which includes Deno (https://github.com/hayd/deno-docker)
FROM hayd/deno:latest AS builder
WORKDIR /bot
COPY . .
# build 
RUN deno compile --unstable --allow-net --allow-read=/bot --allow-write=/bot mod.ts -o mybot 

# Start the run stage
FROM gcr.io/distroless/base-debian10

# Create and move into /bot directory
WORKDIR /bot

# Create a volume to store the database
VOLUME /bot/db

# Copy the build files from first stage to current working directory
COPY --from=builder /bot/mybot .

# Chown the directory and its content so that it belong to Deno user
RUN chown -R deno:deno /bot

# Use user deno so the bot isn't running as root
USER deno

# Finally run the bot
CMD ["mybot"]
`

**Comment by MrEmanuel** [comment]
Thanks for the explanation. I think I understand more how deno and this project works now. 
I also hear what you're saying about the config file. Sounds reasonable not to have it bundled.
Since the most crucial secret is the token, these changes might be good enough in the meantime? It moves the token from the `configs.ts` to a `.env` file and uses `dotenv` to add the variable to the deno process.

`mod.ts` now reads the token from an environment variable instead of `config.ts`. I also updated the README accordingly. Note that the Website/Guide will also need to be updated with the new instructions.

This change also simplified the docker commands and got rid of the confusing `-v` tag. 
I'm not sure it's strictly necessary to move all the other config variables to the `.env` but I'm not to familiar with the discord api yet to really know. Getting the token out of there is a good first step I think.

**Comment by ayntee** [comment]
> Thanks for the explanation. I think I understand more how deno and this project works now.
> I also hear what you're saying about the config file. Sounds reasonable not to have it bundled.
> 
> Since the most crucial secret is the token, these changes might be good enough in the meantime? It moves the token from the `configs.ts` to a `.env` file and uses `dotenv` to add the variable to the deno process.
> 
> `mod.ts` now reads the token from an environment variable instead of `config.ts`. I also updated the README accordingly. Note that the Website/Guide will also need to be updated with the new instructions.
> 
> This change also simplified the docker commands and got rid of the confusing `-v` tag.
> I'm not sure it's strictly necessary to move all the other config variables to the `.env` but I'm not to familiar with the discord api yet to really know. Getting the token out of there is a good first step I think.
> 
> I also removed the build step.

Having a separate file for just the application token does not seem right... @skillz4killz, thoughts?

**Pull request closed without merging**
