### PR TITLE
Add fmt and linter workflow

### PR DESCRIPTION
**Pull request by damfle**
Github Actions #4

### CODE REVIEW

**Comment by itohatweb** [comment]
Generally I have nothing against it and if you want merge it ayntee. But if you do I will stop using the boilerplate.

**Comment by itohatweb** [comment]
I might have phrased this a bit rude, let me explain my point. The deno linter is really bad imo it has stupid rules I don't like and imo make the coding experience worse.

**Comment by ayntee** [comment]
> I might have phrased this a bit rude, let me explain my point. The deno linter is really bad imo it has stupid rules I don't like and imo make the coding experience worse.

I think we should wait for the linter to be stabilized.

**Comment by damfle** [comment]
Linter are annoying by design :)
As ayntee said the rules looks pretty similar to eslint ones. We can still ignore rules that are buggy or don't fit the use case.
I ignored line by line, eg all the async func instead of promises, but we can ignore the entire file and maybe disbale an entire rule soon.

**Comment by itohatweb** [comment]
tbh I hate ignore comments.

**Comment by damfle** [comment]
Yes this is ugly but still better than ignoring an entire rule or the entire file

**Comment by Skillz4Killz** [comment]
Just my 2 cents:

1. I would make sure .vscode has linter disabled by default as its unstable
2. I think if 1 is done the problems itoh mentioned won't occur and the comments are just there. Sure its a few extra unneeded comments but for those that do want a linter once they enable it its better these comments are present.
3. # comment out the linter step temporarily while it is unstable. 

This would make the pr mergeable and useable by anyone. It also adapts to everyones needs imo

**Comment by damfle** [comment]
Good idea. Let me modify my pr

**Comment by ayntee** [comment]
> Just my 2 cents:
> 
>     1. I would make sure .vscode has linter disabled by default as its unstable
> 
>     2. I think if 1 is done the problems itoh mentioned won't occur and the comments are just there. Sure its a few extra unneeded comments but for those that do want a linter once they enable it its better these comments are present.
> 
>     3. `#` comment out the linter step temporarily while it is unstable in the GH Action so users dont get scared why they have errors on github
> 
> 
> This would make the pr mergeable and useable by anyone. It also adapts to everyones needs imo

We can try to remove some of the lint warnings by "fixing" the code; for instance, the `reuiqre-await` rule can be resolved by just removing async from the function.

**Comment by damfle** [comment]
> > Just my 2 cents:
> > ```
> > 1. I would make sure .vscode has linter disabled by default as its unstable
> > 
> > 2. I think if 1 is done the problems itoh mentioned won't occur and the comments are just there. Sure its a few extra unneeded comments but for those that do want a linter once they enable it its better these comments are present.
> > 
> > 3. `#` comment out the linter step temporarily while it is unstable in the GH Action so users dont get scared why they have errors on github
> > ```
> > 
> > 
> > This would make the pr mergeable and useable by anyone. It also adapts to everyones needs imo
> 
> We can try to remove some of the lint warnings by "fixing" the code; for instance, the `require-await` rule can be resolved by just removing async from the function.

I tried this on my bot. This look easy but caller are looking for promises. And the async syntax is more readable

**Review by ayntee — APPROVED** [review]
LGTM ― Thank you!

**Pull request merged**
